theme: jekyll-theme-midnight

title: Cemu Graphic Packs
description: Largest graphic pack source for Cemu that modify or scale games.
author: Cemu graphic pack community
logo: /assets/embed.png
canonical_url: "https://slashiee.github.io/cemu_graphic_packs/"